#
# common definitions for header dependency
# 
PHONY: d_clean

%.o: %.c
	$(COMPILE.c) -MMD -MP $< -o $@

srcs = $(wildcard *.c)
header_deps = $(srcs:.c=.d)
-include $(header_deps)

d_clean:
	rm -f *.d
